# Generated by Django 5.0.1 on 2024-02-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_file_filemedia_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemedia',
            old_name='src',
            new_name='file',
        ),
    ]
