# Generated by Django 5.0.1 on 2024-02-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_story_managers_post_created_story_created_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='story',
            managers=[
            ],
        ),
    ]
