# Generated by Django 5.0.1 on 2024-03-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_add_comment_post_like_post_story_add_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='add_comment',
            new_name='can_add_comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='like_post',
            new_name='can_like',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='add_comment',
            new_name='can_add_comment',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='like_post',
            new_name='can_like',
        ),
    ]
