# Generated by Django 5.0.1 on 2024-01-23 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_groups_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last seen date'),
        ),
    ]
