# Generated by Django 5.0.1 on 2024-01-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_auth',
            field=models.BooleanField(default=False),
        ),
    ]
