# Generated by Django 5.0.1 on 2024-01-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_auth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtpToken',
        ),
    ]
